/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.wangyn.framework.thrift.data;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 响应码的枚举值
 * SUCCESS 表示成功
 * PARAMSERROR 参数错误
 * SERVICEERROR 业务错误
 * SYSTEMERROR 系统异常
 * 
 */
public enum ResultCodeEnum implements org.apache.thrift.TEnum {
  SUCCESS(200),
  PARAMSERROR(201),
  SERVICEERROR(202),
  SYSTEMERROR(999);

  private final int value;

  private ResultCodeEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ResultCodeEnum findByValue(int value) { 
    switch (value) {
      case 200:
        return SUCCESS;
      case 201:
        return PARAMSERROR;
      case 202:
        return SERVICEERROR;
      case 999:
        return SYSTEMERROR;
      default:
        return null;
    }
  }
}
